### ISSUE TITLE
Include date in parser output filenames

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#3]
Lets make the parser easer to use. Don't worry about fancy options or anything, just simple and stream line. Additionally maybe make the output files dated

**Comment by TheBen27** [comment]
Awhile back, I made it print the readme upon incorrect invocation awhile ago, so it's streamlined.
The output files are not dated, but they probably should be... I'm renaming this issue to reflect what's left to do.

**Comment by TheBen27** [comment]
My final format will go something like this:

If the user does not specify the output filenames, the names will follow the format `[tag name]-[date]-[data/header].csv`

**Comment by WLaney** [comment]
I think `[date]-[tag name]-[data/header].csv` would be slightly better. That way computer file systems will but all our data in chronological order. It's really up to you though, and it might be better to have the file system sort the same tags together. 
Also I know I'm kind of splitting hairs here.

**Comment by TheBen27** [comment]
No, that makes more sense. Thanks

**Comment by TheBen27** [comment]
Done with commit [d925b5](https://github.com/WLaney/Arduino_Animal_Tag/commit/d925b5db13afa2866aebc4f1dfb21be0055a7c78)
