### ISSUE TITLE
Accelerometer no longer has gravity component

### ISSUE THREAD

**Issue by d9i** [WLaney/Arduino_Animal_Tag#31]
We talked about this earlier today - making an issue just to be tidy.

a[x,y,z] readings for v3.0 on device 2.2b no longer shows a -1G acceleration for gravity. Maybe the accelerometer's built-in HPF is enabled?

**Comment by TheBen27** [comment]
The same register that sets the accelerometer's range also controls the high-pass filter. If not configured correctly, the tag might enable that filter by accident.

Try re-configuring the tag from scratch with the new Configure sketch and see if the problem persists.

**Comment by d9i** [comment]
worked during testing, works fine now! I guess it was a config thing.
