### ISSUE TITLE
units of pressure in "test_all.ino"

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#40]
The sketch doesn't state the units of pressure. I think it reads out in millibars.

**Comment by WLaney** [comment]
@abbybilenkin Thank you for picking this up! Feel free to just close the issue when it's done.

**Comment by cbilenkin** [comment]
Resolved by most recent commit 0317b44 "Changes sketch to state that the units for pressure are millibars. I looked up the sensor on Sparkfun's website and it does give the pressure in millibars."
