### ISSUE TITLE
clean up main directrory

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#41]
Can we move [compare_gyros](https://github.com/sharkduino/Arduino_Animal_Tag/tree/master/compare_gyros) and [time](https://github.com/sharkduino/Arduino_Animal_Tag/tree/master/time) from the main directory into [miscellaneous sketches](https://github.com/sharkduino/Arduino_Animal_Tag/tree/master/miscellaneous%20sketches)?

**Comment by cbilenkin** [comment]
Resolved by commit dc97d24 "Moves compare_gyros and time from the main directory into miscellaneous sketches."
