### ISSUE TITLE
Checking SD card presents

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#42]
We are having a problem where the tags will take data for a long time span, then stop, and then recorded periodic bursts of data. This problem only seems to happen while the tags are connected to animals so we currently believe that the problem is caused by either the battery or uSD card coming lose, and then occasionally being shock back into place. 

To isolate wether the battery or the uSD card is the cause of the problem I would like a sketch that periodically (~1min) checks if the uSD card is present. If the uSD is present I would like to write the time to it, and if it is not I would like to write the time to EEPROM or some other stable memory.

It would be nice if we just modify the main sketch so we can get sensor data, but that is not necessary.

**Comment by TheBen27** [comment]
Resolved. It turns out that removing and re-inserting the SD card crashes the program, so it is impossible for the SD card to create the problems we are having.
