### ISSUE TITLE
No documented hardened release for 2.1/2.2 tags

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#47]
The v3.1 release is what the [readme](https://github.com/sharkduino/Arduino_Animal_Tag/blob/master/readme.md) says to use to for v2.1/2.2 tags but that code has parser bugs, and the short bug. We need to update this document with the new hardened release

**Comment by TheBen27** [comment]
New release made. It's v3.2 (not v.3.1.1) because of some non-backwards compatible changes to the parser and file format
