### ISSUE TITLE
Add frequency changing to configuration sketch

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#6]
Make it so the frequency of sampling is easy to adjust. Don't worry about under sampling, just throw away the extra data. It's fine

**Comment by TheBen27** [comment]
Decided to add the frequency-changing feature to the configuration sketch.

If the tag is eventually sealed off, we can't use a configuration file, so there's no reason to invest too much time in that. Later, we can put the configuration sketch into the main sketch and facilitate communication through Bluetooth (or USART) while it's charging

**Comment by TheBen27** [comment]
Tested configurable sample rate. The sample rate is about 7ms off consistently, but it was in the original sketch. I added three sample rates: 12.5, 25, and 50Hz. All 3 seem to work, so this issue is closed.
