### ISSUE TITLE
Flash LED when Tag Turns On

### ISSUE THREAD

**Issue by WLaney** [WLaney/Arduino_Animal_Tag#7]
have pin 13 led flash in a distinctive way right when the tag turns on to confirm the code is loaded and working. This will be especially important when we remove the always on power indicator light form the Arduino

**Comment by TheBen27** [comment]
Did the opposite of this: due to the fact that LED 13 is used by SPI, it flashes on when initializing the SD card. To avoid confusion, I decided that if the Arduino *failed* to initialize, it would just blink continuously.

Finally got around to this.
