### ISSUE TITLE
If tag resets, it appends new set of reads to old

### ISSUE THREAD

**Issue by TheBen27** [WLaney/Arduino_Animal_Tag#8]
If the tag is ever reset during operation, it will append the new set of reads to the old file instead of creating a new one. This issue was negligible back when we could manually go in and separate the two sets of reads into two files - but the size and binary nature of the files will make this difficult, especially for the end users.

**Comment by WLaney** [comment]
I think we should make sure that it puts information into the file letting us know the reset happened

**Comment by TheBen27** [comment]
In a sense, that already happens automatically - the header is written on each reset. We can have the parser split the input into multiple files and warn the user that it happened.

The alternative is to have the Arduino itself create new files upon resetting. Our philosophy so far has been to keep the raw data opaque and have the user use the parser, so it's easier for us to use the parser.

**Comment by TheBen27** [comment]
Arduino now creates new files upon resetting. I know what I said, but the Arduino code's easier to change than the horrid parser code. For now, consider the issue closed.
